<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatest()
    {
        $queryBuilder = $this->createQueryBuilder('p')
                             ->addSelect('p', 'c')
                             ->leftJoin('p.category', 'c');

        return $queryBuilder->getQuery()->getResult();
    }
}
